### ISSUE TITLE
Portuguese & Spanish & Japanese GTFS and GTFS-rt reference.md up & need review!

### ISSUE THREAD

**Issue by heidiguenin** [MobilityData/transit#41]
The Portuguese (Brazil) and Spanish (Latin America) translations of the reference.md files are up for both [GTFS static](https://github.com/MobilityData/transit/tree/master/gtfs/spec) and [GTFS-realtime](https://github.com/MobilityData/transit/tree/master/gtfs-realtime/spec). If you have the ability to review or can connect with folks who can review, please do!

**Comment by barbeau** [comment]
cc @Cristhian-HA @scmcca Are these translations still useful?

**Comment by Cristhian-HA** [comment]
I would say yes what about you @scmcca ?

**Comment by barbeau** [comment]
@scmcca Good question. At one point MobilityData created a Transifex account (free for OSS):
https://www.transifex.com/mobilitydata/public/

Looks like there is some work for gtfs.org and GTFS reference.

I think this issue is related to the GTFS reference link:
https://www.transifex.com/mobilitydata/gtfs-reference-translations/

Looks like there are completed Portuguese, Spanish AND Japanese translations.

![image](https://user-images.githubusercontent.com/928045/158643400-15ae0a93-3260-464e-bf78-586a13ec4b27.png)

**Comment by emmambd** [comment]
Outdated. Translations in these languages are available at https://github.com/MobilityData/gtfs.org and can be updated and improved there.
